# Generated by Django 6.0.3 on 2026-03-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.TextField()),
                ('diagnostico', models.TextField(blank=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('diagnostico', 'Diagnóstico'), ('aprovacao', 'Aguardando aprovação'), ('reparo', 'Em reparo'), ('finalizado', 'Finalizado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='recebido', max_length=20)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.equipamento')),
            ],
        ),
    ]
