# Generated by Django 6.0.3 on 2026-03-14 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_equipamento_ordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='garantia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('diagnostico', 'Diagnóstico'), ('aprovacao', 'Aguardando Aprovação'), ('reparo', 'Em Reparo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='recebido', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
